// "use client"
import Layout from "@/components/layout/Layout";
import "@/app/globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>

        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
