
import "@/app/globals.css";
import ModalMain from "@/components/template/ModalMain";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        {/* <ModalMain /> */}
      </body>
    </html>
  );
}
